### ISSUE TITLE
BG001  Verify if the login page is accessible.

### ISSUE THREAD

**Issue by gopika2007-art** [gmartha632/Cartly#1]
The login page should be displayed with "Email" and "Password" fields and "Sign In" button. But it only login button shows.

**Comment by gmartha632** [comment]
IT is login button only  , mistakenly it was displayed as sign in  option rather than login  in  sign up page . It i s fixed.

**Comment by gopika2007-art** [comment]
ok i will recheck it

**Comment by gopika2007-art** [comment]
the bug was fixed
